#!/usr/bin/env bash
# Generate the Homebrew formula for @@NAME@@ from a release checksums.txt.
#
# Usage:
#   scripts/generate-formula.sh VERSION CHECKSUMS_FILE > @@NAME@@.rb
#
# Args:
#   VERSION         release version without the v prefix (e.g. 0.1.0)
#   CHECKSUMS_FILE  path to the release checksums.txt (sha256sum format)
#
# Release CI runs this to update Formula/@@NAME@@.rb in
# https://github.com/@@OWNER@@/homebrew-tap on every release.

set -euo pipefail

err() { printf 'error: %s\n' "$*" >&2; exit 1; }

[ $# -eq 2 ] || err "usage: $0 VERSION CHECKSUMS_FILE"

version="$1"
checksums="$2"

[ -f "$checksums" ] || err "checksums file not found: $checksums"

sha_for() {
  local target="$1" sha
  sha=$(awk -v f="@@NAME@@_${version}_${target}.tar.gz" '$2 == f { print $1 }' "$checksums")
  [ -n "$sha" ] || err "no checksum for @@NAME@@_${version}_${target}.tar.gz in ${checksums}"
  printf '%s' "$sha"
}

darwin_amd64=$(sha_for darwin_amd64)
darwin_arm64=$(sha_for darwin_arm64)
linux_amd64=$(sha_for linux_amd64)
linux_arm64=$(sha_for linux_arm64)

cat <<EOF
# This file is generated by scripts/generate-formula.sh in
# https://github.com/@@OWNER@@/@@REPO@@. DO NOT EDIT.
class @@CLASS@@ < Formula
  desc "@@DESC@@"
  homepage "@@HOMEPAGE@@"
  version "${version}"
  license "MIT"

  livecheck do
    skip "Formula is updated by @@NAME@@ release CI"
  end

  on_macos do
    on_intel do
      url "https://github.com/@@OWNER@@/@@REPO@@/releases/download/v${version}/@@NAME@@_${version}_darwin_amd64.tar.gz"
      sha256 "${darwin_amd64}"
    end
    on_arm do
      url "https://github.com/@@OWNER@@/@@REPO@@/releases/download/v${version}/@@NAME@@_${version}_darwin_arm64.tar.gz"
      sha256 "${darwin_arm64}"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/@@OWNER@@/@@REPO@@/releases/download/v${version}/@@NAME@@_${version}_linux_amd64.tar.gz"
      sha256 "${linux_amd64}"
    end
    on_arm do
      url "https://github.com/@@OWNER@@/@@REPO@@/releases/download/v${version}/@@NAME@@_${version}_linux_arm64.tar.gz"
      sha256 "${linux_arm64}"
    end
  end

  def install
    bin.install "@@NAME@@"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/@@NAME@@ --version")
  end
end
EOF
